### PR TITLE
FE-517: Added custom time form

### PR DESCRIPTION
**Pull request by itolegmysin**

### CODE REVIEW

**Comment by svanscho** [comment]
General remarks:
- can we have a screenshot so I can see the final result?
- is there a message somewhere describing the backup window is in the timezone of the gateway/installation?

**Comment by itolegmysin** [comment]
@svanscho 
image
image

**Comment by iOlivier** [comment]
Looks good, but I would change the copy a bit:

Screenshot 2021-04-02 at 11 48 10
Screenshot 2021-04-02 at 11 49 05

**Comment by svanscho** [comment]
@itolegmysin @iOlivier 
- taken by: OpenMotics Cloud ? (just a suggestion, I'm fine with anything it just avoids repetition of the description)
- what is the automatic time? we don't have that on the backend, we just have enabled/disabled. Can we change this?

**Comment by iOlivier** [comment]
> @itolegmysin @iOlivier
> 
> * taken by: **OpenMotics Cloud** ? (just a suggestion, I'm fine with anything it just avoids repetition of the description)
> * what is the automatic time? we don't have that on the backend, we just have enabled/disabled. Can we change this?

Euhm, well what do this fields mean then? Because it's added to the postman docs

**Comment by svanscho** [comment]
image

**Comment by itolegmysin** [comment]
@svanscho @iOlivier 
> what is the automatic time? we don't have that on the backend, we just have enabled/disabled. Can we change this?
When user selected automatic time I send to backend these values:
image

**Review by iOlivier — APPROVED** [review]

**Pull request merged**
