### PR TITLE
PO-396: Added new sensor value into dropdown

### PR DESCRIPTION
**Pull request by itolegmysin**

### CODE REVIEW

**Comment by itolegmysin** [comment]
image

**Comment by iOlivier** [comment]
@khenderick Can we just add the value in the middle and create a migration script for the db or do we add this new value at the end?

**Comment by khenderick** [comment]
It would be nicer to have them ordered by size. But most important is that the value saved to the backend makes sense according to this overview:

* 8: 2 = 25A, 3 = 50A
* 12: 2 = 12.5A, 3 = 25A, 4 = 50A, 5 = 100A, 6 = 200A. With any other value, you just pass the value itself, so 150 = 150.

**Comment by itolegmysin** [comment]
@khenderick could you please check latest changes

**Comment by khenderick** [comment]
Looks good

**Review by iOlivier — APPROVED** [review]

**Pull request merged**
