### PR TITLE
PO-39: Create edit page floors plans

### PR DESCRIPTION
**Pull request by itolegmysin**

### CODE REVIEW

**Comment by khenderick** [comment]
I don't see obvious issues, so looks ok to me.

**Comment by iOlivier** [comment]
Screenshot 2020-03-27 at 16 04 09

This checkbox doesn't look so user friendly.
I would in fact hide the complete bottom bar and only show this if the user clicks the "Edit" button.

**Comment by iOlivier** [comment]
I also can't seem to drag and drop from the bar to the floor plan. Am I doing something wrong?

**Comment by khenderick** [comment]
@iOlivier, the user must be able to always see all relevant outputs/lights, even those not yet moved to the floor plan. So if you don't want to have the checkbox, you must always show them.

This checkbox was off by default in the past since the cloud did show a lot of technical outputs (such as valves etc), but at this moment we support more output types (such as valve). These are already hidden by default in the v1 api, so I'd rather suggest to always (and only) show outputs/lights with types light (255), output (0) and appliance (3)

**Comment by iOlivier** [comment]
> @iOlivier, the user must be able to always see all relevant outputs/lights, even those not yet moved to the floor plan. So if you don't want to have the checkbox, you must always show them.
> 
> This checkbox was off by default in the past since the cloud did show a lot of technical outputs (such as valves etc), but at this moment we support more output types (such as valve). These are already hidden by default in the v1 api, so I'd rather suggest to always (and only) show outputs/lights with types light (255), output (0) and appliance (3)

I'm not sure I understand why the user would always want to see them. Why would you want to show all devices that are not linked to the floor plan? If one is missing, he can press "Edit" and just add them, right?
I don't want to remove the checkbox functionality, I just want it to be behind an edit/show button.

**Comment by iOlivier** [comment]
@itolegmysin 

Screenshot 2020-04-01 at 10 30 59

I would not put the button in the middle of the sentence, this looks weird.
Can you put the button in front of the sentence please?
I would also toggle the button text from "Enter edit mode" to "Exit edit mode" and visa versa.

**Comment by khenderick** [comment]
> I'm not sure I understand why the user would always want to see them. Why would you want to show all devices that are not linked to the floor plan? If one is missing, he can press "Edit" and just add them, right?
> I don't want to remove the checkbox functionality, I just want it to be behind an edit/show button.
On second thought, I can't think of a reason not to add such entries to the plan, so that's fine for me.

**Comment by iOlivier** [comment]
As discussed in our call after the demo meeting:
- Remove an item from the floor plan
- Toggle dimmable lights
- Check toggle colour on outlets

**Comment by iOlivier** [comment]
> As discussed in our call after the demo meeting:
> 
> * Remove an item from the floor plan
> * Toggle dimmable lights

- [x] Remove an item from the floor plan
- [ ] Toggle dimmable lights

**Pull request merged**
