### PR TITLE
PO-44: Thermostats configuration

### PR DESCRIPTION
**Pull request by itolegmysin**

### CODE REVIEW

**Comment by khenderick** [comment]
Is this validated on both cloud and gateway target?

**Comment by iOlivier** [comment]
Don't forget to remove the old scrollers:

Screenshot 2020-04-08 at 17 57 24

**Comment by iOlivier** [comment]
Can you check the heating/cooling switch width please?

Screenshot 2020-04-10 at 10 34 06

**Comment by itolegmysin** [comment]
> Can you check the heating/cooling switch width please?
> 
> Screenshot 2020-04-10 at 10 34 06

Done

**Comment by itolegmysin** [comment]
> Don't forget to remove the old scrollers:
> 
> Screenshot 2020-04-08 at 17 57 24

Done

**Comment by itolegmysin** [comment]
> Is this validated on both cloud and gateway target?

Seems like I (itolegmysin@gmail.com) don't have any configurable thermostat

**Comment by khenderick** [comment]
Ping me today and we'll point your dev gateway to our staging environment. There you can add thermostats as then validate them on the local gateway interface.

**Comment by iOlivier** [comment]
Screenshot 2020-04-15 at 10 45 55

See screenshot above!

- In the "red square", it's hard to see which thermostat is cooling and which one is heating.
- I would suggest that we only show the configuration of the selected thermostat (= orange square)
- Then we can remove the listing on the bottom of the screen

**Pull request merged**
