### PR TITLE
PO-363: Fixed supplier save with double tariff

### PR DESCRIPTION
**Pull request by itolegmysin**

### CODE REVIEW

**Comment by iOlivier** [comment]
Screen Shot 2020-11-25 at 16 00 31

Screen Shot 2020-11-25 at 16 01 34

**Comment by iOlivier** [comment]
The scrollers are not visible when adding a new supplier:
image

**Comment by iOlivier** [comment]
There is still an additional input field missing for the "double tariff price".
See the network call to find the exact field.

image

**Comment by itolegmysin** [comment]
@iOlivier 
I added a peak price field :heavy_check_mark: 
For the scrollers I'd leave them into edit section otherwise I'm not sure where I should placed them (probably you can send a some layout) :thinking:

**Comment by iOlivier** [comment]
Screen Shot 2020-11-30 at 14 54 40

**Review by iOlivier — APPROVED** [review]

**Pull request merged**
